- hosts: localhost
  connection: local
  gather_facts: no
#  vars_files:
#    - "group_vars/all.yml"
#  roles:
#    - homebrew


  tasks:
  - name: install homebrew packages
    homebrew: name="{{ item.name }}" state="{{ item.state|default('latest') }}" install_options="{{ item.install_options|default() }}"
    with_items:
      - { name: "htop" }
      - { name: "tree" }
      - { name: "git" }
      - { name: "svn" }
      - { name: "skype" }
      - { name: "slack" }
      - { name: "vagrant" }
      - { name: "skitch" }
      - { name: "virtualbox" }
      - { name: "xmind" }
      - { name: "google-chrome" }
      - { name: "google-japanese-ime" }
      - { name: "macdown" }
      - { name: "atom" }
      - { name: "firefox" }
      - { name: "evernote" }

