- name: Update Homebrew
  homebrew:
    state: latest
    update_homebrew: yes

- name: Install Homebrew Packages
  homebrew:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ brew_packages }}"
